module "pubsub-service-account" {
  source = "../../pubsub-service-account"

  project_id   = var.project_id
  namespace    = var.namespace
  service_name = var.service_name
}

module "notification-service-db" {
  source = "../../cloudsql-resources"

  cloud_sql_instance_connection_name = var.cloud_sql_instance_connection_name
  cloud_sql_instance_name            = var.cloud_sql_instance_name
  cloudsql_service_account_key       = var.cloudsql_service_account_key
  database_name                      = var.database_name
  namespace                          = var.namespace
}

resource "kubernetes_secret" "firebase-database-url" {
  metadata {
    name      = "firebase-database-url"
    namespace = var.namespace
  }

  data = {
    FIREBASE_DATABASE_URL = var.firebase_database_url
  }
}

resource "kubernetes_config_map_v1" "service-account-config-map" {
  metadata {
    name      = "${var.service_name}-service-account"
    namespace = var.namespace
  }

  data = {
    "key.json" = base64decode(module.pubsub-service-account.service_account_key)
  }
}

# Replace the service account name appropriately according to the one generated by firebase project
# For more info, refer to https://console.firebase.google.com/u/1/project/fitcentive-dev/settings/serviceaccounts/adminsdk
resource "google_service_account_key" "firebase-admin-service-account-key" {
  service_account_id = var.firebase_admin_service_account
  public_key_type    = "TYPE_X509_PEM_FILE"
}

resource "kubernetes_secret" "firebase-admin-service-account-credentials" {
  metadata {
    name      = "firebase-admin-service-account-credentials"
    namespace = var.namespace
  }
  data = {
    FIREBASE_APPLICATION_CREDENTIALS = base64decode(google_service_account_key.firebase-admin-service-account-key.private_key)
  }
}

resource "kubernetes_secret" "smtp-credentials" {
  metadata {
    name      = "smtp-credentials"
    namespace = var.namespace
  }
  data = {
    smtp_user     = var.smtp_user
    smtp_password = var.smtp_password
    smtp_host     = var.smtp_host
    smtp_port     = var.smtp_port
  }
}