resource "google_sql_database" "notification-service-db" {
  name     = "${var.service_name}-db"
  instance = var.cloud_sql_instance_name
}

module "pubsub-service-account" {
  source = "../../pubsub-service-account"

  project_id   = var.project_id
  namespace    = var.namespace
  service_name = var.service_name
}

resource "kubernetes_secret" "firebase-database-url" {
  metadata {
    name      = "firebase-database-url"
    namespace = var.namespace
  }

  data = {
    FIREBASE_DATABASE_URL = var.firebase_database_url
  }
}

# Replace the service account name appropriately according to the one generated by firebase project
# For more info, refer to https://console.firebase.google.com/u/1/project/place-2-meet-dev/settings/serviceaccounts/adminsdk
resource "google_service_account_key" "firebase-admin-service-account-key" {
  service_account_id = var.firebase_admin_service_account
  public_key_type    = "TYPE_X509_PEM_FILE"
}

resource "kubernetes_secret" "firebase-admin-service-account-credentials" {
  metadata {
    name      = "firebase-admin-service-account-credentials"
    namespace = var.namespace
  }
  data = {
    FIREBASE_APPLICATION_CREDENTIALS = base64decode(google_service_account_key.firebase-admin-service-account-key.private_key)
  }
}