= GKE DEV Environment

== Pre-requisites
1. Read the `README.adoc` and Execute `tf apply` in the parent `nonproduction` project
2. 2. After doing `tf apply` in `nonproduction`, update the contents of `resources/terraform_service_account.json` with the contents of `terraform output -raw tf_service_account_private_key | base64 --decode`
    - `terraform output -raw tf_service_account_private_key | base64 --decode > ../../gke-dev-env/resources/terraform_service_account.json`
    - This is the service account identity that the `google` terraform provider will now assume
3. Target apply the firebase module before proceeding with everything else
    - `terraform apply -target module.dev-firebase-project`
4. Replace the value `firebase_admin_service_account` in the  with the right service account ID as generated by the `firebase` module
    - Look for `Firebase service account` value at https://console.firebase.google.com/u/1/project/place-2-meet-dev/settings/serviceaccounts/adminsdk
[source,hcl]
----
include::./terraform/main.tf[lines=144..147]
----
