= GKE DEV Environment

== Pre-requisites
1. Read the `README.adoc` and Execute `tf apply` in the parent `nonproduction` project
2. Replace the value `firebase_admin_service_account` in `locals-data.tf` the  with the right service account ID as generated by the `dev-firebase-project` module in the `nonproduction` parent project
    - Look for `Firebase service account` value at https://console.firebase.google.com/u/1/project/fitcentive-dev/settings/serviceaccounts/adminsdk
    - This value is currently not supported as an attribute that can be exported via terraform outputs
+
[source,hcl]
----
include::./terraform/locals-data.tf[lines=27..31]
----



== Applying changes
1. `tf apply`
    - Creating GKE cluster takes time, ~10 mins


== Post apply changes
1. Navigate to the keycloak server and create a password for the admin account
    - http://auth.fitcentive.xyz/auth
    - Keep track of this password!
2. Navigate to the keycloak server, login as admin, and generate client-secret for `admin-cli` client in the `master` realm
    - Login as admin to http://auth.fitcentive.xyz/auth
    - Navigate to the `master` realm
    - Navigate to clients and select the `admin-cli` client
    - Toggle client accessibility from `public` to `confidential`, hit save.
    - Navigate to the credentials tab and copy over the generated `client-secret`
3. Navigate to `locals-data.tf` and update the values for the following keys based on the values from above
    - `keycloak_admin_client_secret`
    - `keycloak_admin_client_password`
+
[source,hcl]
----
include::./terraform/locals-data.tf[lines=34..41]
----
4. Navigate to the keycloak server and fetch the required info in the quoted block below
+
[source,hcl]
----
include::./terraform/locals-data.tf[lines=44..64]
----
5. Run `tf apply` again to apply the changes
    - Ensure the `auth-service` secrets are updated
    - Might require a manual pod restart to ensure new secret is picked up


== FAQS
1. CORS issue with authentictation
    - Add web origin to `Web origins` section of `webapp` client for the appropriate keycloak realm