#--------------------------------------------------------------------------
# Custom values for prometheus-community/kube-prometheus-stack helm chart
# kube-prometheus-stack: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
# Prometheus: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
#--------------------------------------------------------------------------

fullnameOverride: ${HELM_KUBEPROMSTACK_RELEASE_NAME}

prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: 250m
        memory: 500Mi
      limits:
        cpu: 500m
        memory: 1Gi

    retention: 7d

kubelet:
  serviceMonitor:
    # kubernetes 1.18+ resourcePath value must be "/metrics/resource"
    resourcePath: "/metrics/resource"
