= GKE DEV Environment

== Pre-requisites
1. Read the `README.adoc` and Execute `tf apply` in the parent `nonproduction` project
2. Replace the value `firebase_admin_service_account` in `locals-data.tf` the  with the right service account ID as generated by the `dev-firebase-project` module in the `nonproduction` parent project
    - Look for `Firebase service account` value at https://console.firebase.google.com/u/1/project/fitcentive-dev/settings/serviceaccounts/adminsdk
    - This value is currently not supported as an attribute that can be exported via terraform outputs
+
[source,hcl]
----
include::./terraform/locals-data.tf[lines=31..35]
----



== Applying changes
1. `tf apply`
    - Creating GKE cluster takes time, ~10 mins


== Post apply changes
. Update Google Cloud domains to point to LoadBalancer Static IP address `nonproduction.outputs.gke_dev_gke_regional_static_ip_address`
. Navigate to the keycloak server and create a password for the admin account
    - http://auth.fitcentive.xyz/auth
    - Keep track of this password!
. Navigate to the keycloak server, login as admin, and generate client-secret for `admin-cli` client in the `master` realm
    - Login as admin to http://auth.fitcentive.xyz/auth
    - Navigate to the `master` realm
    - Navigate to clients and select the `admin-cli` client
    - Toggle client accessibility from `public` to `confidential`, hit save.
    - Navigate to the credentials tab and copy over the generated `client-secret`
. Navigate to `locals-data.tf` and update the values for the following keys based on the values from above
    - `keycloak_admin_client_secret`
    - `keycloak_admin_client_password`
+
[source,hcl]
----
include::./terraform/locals-data.tf[lines=38..45]
----
. Navigate to the keycloak server and fetch the required info in the quoted block below
+
[source,hcl]
----
include::./terraform/locals-data.tf[lines=48..68]
----
. https://platform.fatsecret.com/api/Default.aspx?screen=myc[Navigate to the Fatsecret UI in the browser] and fetch clientId/clientSecret and update below referenced values
+
[source,hcl]
----
include::./terraform/locals-data.tf[lines=70..73]
----
. https://apps.admob.com/v2/apps/list[Navigate to the AdMob UI in the browser] and create/fetch the appropriate ad unit ids as needed
+
[source,hcl]
----
include::./terraform/locals-data.tf[lines=75..77]
----
. Run `tf apply` again to apply the changes
    - Ensure the `auth-service` secrets are updated
    - Might require a manual pod restart to ensure new secret is picked up


== FAQS
1. CORS issue with authentication
    - Add web origin to `Web origins` section of `webapp` client for the appropriate keycloak realm

== Migrate between GCP environments
. Backup existing CloudSQL instance
    - Navigate to CloudSQL via GCP console
    - Select `export`
. Backup existing buckets in GCS
    - Terraform state buckets
    - `image-service-upload-images`
    - `cloud-sql-pgdump`
. Create new GCP project in the GCP console
. Use gcloud to create new credentials via terminal.
    - `gcloud auth login` - with the new GCP account
    - `gcloud config configurations create fitcentive-dev-02`
    - `gcloud config set account <emailId>@gmail.com`
    - `gcloud config set project fitcentive-dev-02`
    - `gcloud config configurations activate fitcentive-dev-02`
    - `gcloud config set compute/zone northamerica-northeast2-a`
    - `gcloud config list`
    - `gcloud auth application-default login` - with the new GCP account
. Follow README instructions
. Import GCS buckets that were exported previously
    - NOTE - Owing to differences in file-system between GCS and UNIX, folders might not show up on the mount despite existing in GCS
    - Quick fix is to use `mkdir` to create all existing GCS "directories" so the mount is aware of files within them
    - Elegant fix would be to further investigate the option `gcsfuse` provides `--implicit-dirs` - but this does not seem to work as expected
. https://cloud.google.com/sql/docs/postgres/import-export/import-export-sql#console_1[Restore CloudSQL instance using the following docs]
. Update flutter app GoogleServices credentials for push notifications

== Instructions for migration of Keycloak data
. Connect to the old `keycloak-helm-db` schema via IntelliJ
. Export as SQL scripts - include create table expressions
. Global replace `create table` with `create table if exists `
. Global replace `create index` with `create index if exists `
. Via IntelliJ, execute SQL scripts against the `public` schema in `keycloak-helm-db`
    - Execute these scripts 3-4 times, until all data is inserted
    - Make sure it is executed on top of existing created definitions
    - It is required to do it multiple times because some tables/expressions depend on others
. If done correctly, Keycloak auth server will not ask you to reconfigure an admin password, and same values from previous keycloak server can be reused (includes clientId/publicKeys for realms as well)
. **NOTE: Identity Providers for OIDC logins need to be reconfigured - ** For example, it might be required to update the client secret for the Google Identity Provider in the `GoogleAuth` realm.
    - Find this value in the OIDC client provider settings portal.
    - This is needed as secret values aren't automatically migrated over as part of above operations
    - https://github.com/ChathuminaVimukthi/Keycloak-with-Apple-Signin#how-to-configure[Apple IdP configuration instructions]
    - Re apply client secret for Facebook/Apple providers as well as Google provider

