controller:
  service:
    loadBalancerIP: ${STATIC_LOAD_BALANCER_IP_ADDRESS}
defaultBackend:
  enabled: true
  image:
    repository: gcr.io/${GCP_PROJECT_ID}/${HELM_NAME}-default-backend
    tag: "1.0"
    pullPolicy: Always
    readOnlyRootFilesystem: false
  port: 8080